#!/usr/bin/env bash

# Make the script executable
chmod +x wia-infrastructure/build_dev_environment

# Remove Windows line endings if present
sed -i -e 's/\r$//' wia-infrastructure/build_dev_environment

cd wia-infrastructure
./build_dev_environment
cd ..

docker exec -it wia_mysql8 mysql -h 182.80.0.100 -u root -p'12345' -e "CREATE DATABASE IF NOT EXISTS wia CHARACTER SET utf8 COLLATE utf8_general_ci;"
docker exec -it wia_mysql8 mysql -h 182.80.0.100 -u root -p'12345' -e "CREATE DATABASE IF NOT EXISTS wia-testing CHARACTER SET utf8 COLLATE utf8_general_ci;"
docker exec wia_workspace sh -c "cd /var/www/html/wia/wia-api && composer install && php artisan migrate && php artisan migrate --env=testing"
docker exec wia_workspace sh -c "cd /var/www/html/wia/wia-spa && npm i && npm run build"
docker exec wia_workspace sh -c "/usr/bin/supervisord"
